Refactor Release Object Ordering
SFDO-Tooling/MetaCI pull request #1813
Opened 2020-12-12 09:33 UTC by jofsky

2020-12-14 15:37 UTC, davisagli requested changes

2020-12-14 15:37 UTC, davisagli commented on metaci/release/models.py
> +        ordering = ["-git_tag"]
This won't work right -- the sorting for a text field is alphabetical, so a tag like release/9 will sort before release/10 in descending order.

If the goal is to show the most recently created release first, I'd suggest `-created`

2020-12-14 15:38 UTC, davisagli commented on metaci/release/models.py
> +        ordering = ["-git_tag"]
You'll also need to add a migration.

2020-12-15 15:08 UTC, davisagli commented
@jofsky whenever you change a model, you need to generate a new migration so that Django can keep track of whether other instances of the project need to have their databases updated.

Run `./manage.py makemigrations -n NAME` where NAME is a brief description of what changed (e.g. `release_ordering` in this case). Then run black on the resulting migration file and commit it.

2020-12-15 15:09 UTC, davisagli commented
Django docs on migrations, for more info: https://docs.djangoproject.com/en/3.1/topics/migrations/

2020-12-15 21:49 UTC, jofsky commented
Ah shoot, I forgot to commit it before requesting. Although I will read the docs. @davisagli

2020-12-16 14:14 UTC, davisagli approved these changes

2020-12-16 14:14 UTC, merged