Blank regex fix
SFDO-Tooling/MetaCI pull request #1979
Opened 2021-02-10 20:04 UTC by Br4nd0R

2021-02-11 22:25 UTC, davisagli requested changes

2021-02-11 22:25 UTC, davisagli commented on metaci/repository/views.py
> +            logger.warn(
```suggestion
            logger.warning(
```

(warn works but is deprecated)

2021-02-11 22:26 UTC, davisagli reviewed
Looks great. I didn't actually QA it -- should I?

2021-02-12 19:47 UTC, Br4nd0R commented
> Looks great. I didn't actually QA it -- should I?

I've QA'ed the Admin UI portion already. Per our conversation in slack, I can QA that plans get skipped and logging is output in staging.

2021-02-12 19:59 UTC, davisagli approved these changes
Merge when you're ready

2021-02-12 20:14 UTC, merged