Documentation and tools for simplifying configuration.
SFDO-Tooling/MetaCI pull request #2051
Opened 2021-03-06 04:00 UTC by prescod

Small documentation reorg and a new tool for partially validating settings.

2021-03-09 15:34 UTC, davisagli requested changes

2021-03-09 15:34 UTC, davisagli commented on docs/configuring.rst
> +===================
```suggestion
==================
Configuring MetaCI
==================
```

2021-03-09 15:34 UTC, davisagli commented on docs/configuring.rst
> +---------------
The vars in this section aren't really intended to be modified; I'd be inclined to take this section out.

2021-03-09 15:34 UTC, davisagli commented on docs/configuring.rst
> +Build Arguments
Clarify that these are only used when building the Docker image

2021-03-09 15:34 UTC, davisagli commented on metaci/users/management/commands/verify_environment.py
> +                "Devhub is not configured. Scratch org creation will fail",
```suggestion
                "Dev Hub seems to be configured",
                "Dev Hub is not configured. Scratch org creation will fail",
```

2021-03-09 15:34 UTC, davisagli commented on metaci/users/management/commands/verify_environment.py
> +                "Github API is not configured. Repos cannot be retrieved for builds.",
```suggestion
                "GitHub API is configured",
                "GitHub API is not configured. Repos cannot be retrieved for builds.",
```

2021-03-09 15:34 UTC, davisagli commented on metaci/users/management/commands/verify_environment.py
> +                errors.append(bad + f": {e}")
```suggestion
                errors.append(f"{bad}: {e}")
```

2021-03-09 15:34 UTC, davisagli commented on metaci/users/management/commands/verify_environment.py
> +    # is there a way to test this with no user interaction?
Not without the instance_url and username of a user that has already approved the connected app

2021-03-09 20:47 UTC, Br4nd0R commented on docs/configuring.rst
> +    their account a `personal access token` will be used when Multi Factor Authentication is enabled.
```suggestion
    their account. A `personal access token` will be used when Multi Factor Authentication is enabled.
```

2021-03-09 20:56 UTC, Br4nd0R approved these changes
lgtm!

2021-03-09 22:49 UTC, prescod commented
Unfortunately I can't see what Snyk dislikes about my build. Is it an orthogonal dependency problem?

2021-03-09 23:55 UTC, Br4nd0R commented
> Unfortunately I can't see what Snyk dislikes about my build. Is it an orthogonal dependency problem?

I'm having the same problem on a Dependency PR for MetaDeploy. It is not clear at all what Snyk is actually complaining about, it tells me a file that it doesn't like but I can't find a specific error message. And I don't have access on this repo to confirm if this is the same thing I'm seeing. I'll let you know if I find out anything.

2021-03-10 00:06 UTC, davisagli commented
@Br4nd0R You should have access to see MetaCI in snyk, from what I can see. @prescod, your status shows as "pending"; I think may have just sent you an invite that you have to accept but the UI is confusing.

In this case it looks clear to me what it's complaining about -- there are 2 dependencies which need to be updated. But they aren't related to this PR and I think we can go ahead and merge this and then update them separately. @Br4nd0R the problem in MetaDeploy where it wasn't showing the actual problem turned out to be a problem parsing base.txt because it listed the same package twice -- I figured it out because the CircleCI build was not running due to needing to be reset after we enabled SSO, and then once it ran it showed the error reading base.txt

2021-03-10 14:52 UTC, davisagli approved these changes
Thanks!

2021-03-10 14:52 UTC, merged