Feature/push time injection
SFDO-Tooling/MetaCI pull request #2488
Opened 2021-07-28 16:47 UTC by jofsky

2021-07-28 17:58 UTC, davisagli reviewed
What's the reason for this? Is it to make sure the push gets scheduled immediately rather than a short time in the future?

2021-07-28 17:58 UTC, davisagli commented on metaci/repository/models.py
> +    default_implementation_steps = models.JSONField(null=True, default=list)
These last 2 files duplicate the changes in #2487; were you intending to submit them there or here?

2021-07-28 23:25 UTC, jstvz commented
@jofsky I would like to suggest that we fix the push task upstream so that it handles ISO-8601 correctly (see [W-9634243](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000RpEPYA0/view)), before we add the mis-formatted datetime here.

2021-07-29 16:47 UTC, jstvz commented
> @jofsky I would like to suggest that we fix the push task upstream so that it handles ISO-8601 correctly (see [W-9634243](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000RpEPYA0/view)), before we add the mis-formatted datetime here.

PR: SFDO-Tooling/CumulusCI#2769

2021-07-30 15:22 UTC, davisagli requested changes

2021-07-30 15:22 UTC, davisagli commented on metaci/build/models.py
> +                raise Exception(f"Ensure that you have declared an implementation step with the {self.build.plan.role}.")
Since we're filtering by plan id, we should probably mention the expected plan name rather than a role?

2021-07-30 15:22 UTC, davisagli commented on metaci/build/models.py
> +                raise Exception(f"Ensure that you have declared an implementation step with the {self.build.plan.role}.")
Ditto

2021-07-30 15:22 UTC, davisagli commented on metaci/build/tests/test_models.py
> +    #     assert options["push_all"]["version"] == "1.0"
Can you update or remove these commented tests?

2021-07-30 15:22 UTC, davisagli commented on metaci/repository/migrations/0009_default_implementation_steps.py
> +            field=models.JSONField(default=list, null=True),
Why are you modifying an existing migration that is not related to the changes in this PR?

2021-08-06 13:19 UTC, davisagli commented on metaci/build/models.py
> +                raise Exception(f"Ensure that you have declared an implementation step the plan {self.build.plan.name}.")
```suggestion
                raise Exception(f"Ensure that you have declared an implementation step with the plan {self.build.plan.name}.")
```

2021-08-06 13:20 UTC, davisagli commented on metaci/release/models.py
> +    push_time: int
This should have a default value of None so that we aren't forced to enter it for default implementation steps that aren't push upgrades.

2021-08-06 13:21 UTC, davisagli commented on metaci/release/models.py
> +        return start + datetime.timedelta(hours=self.push_time)
return None if push_time is None

2021-08-11 13:17 UTC, davisagli commented on metaci/build/tests/test_models.py
> +        with pytest.raises(Exception):
This is way too careless. There could be an exception on the very first statement and the test would pass. This should go around only the statement where the exception is expected, and you should use `with pytest.raises(Exception, match="some text")` to make sure the exception is the one we expected and not something else.

2021-08-12 12:22 UTC, davisagli approved these changes

2021-08-12 12:23 UTC, merged