🛢 [MetaCI] Adding rough draft of release cohort
SFDO-Tooling/MetaCI pull request #2609
Opened 2021-09-14 22:16 UTC by jofsky

2021-09-14 22:46 UTC, Br4nd0R commented
This ligtm; seems like it's covering all AC mentioned in: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000UdnYYAS/view

The third AC does mention:

> A Release has its own Merge Freeze Start and Merge Freeze End fields which are optional overrides for the Release's Cohort dates.

Is anything needed to make these fields "override" release cohorts merge freeze values? Or is the precense of the field on the Release object all we're looking for here? cc @davisagli

2021-09-15 14:22 UTC, jofsky commented
@Br4nd0R I assumed the cci task we create to cover merge freeze will pass in these fields depending on their presence i.e. follow the following logic, if product specific merge freeze start and stop dates are used we will use those otherwise we will pass in the Cohort values as the default when no values are defined. @davisagli 

@Br4nd0R something similar to https://github.com/SFDO-Tooling/MetaCI/blob/main/metaci/build/models.py#L698

2021-09-15 14:31 UTC, davisagli commented
@Br4nd0R @jofsky when we discussed on Monday we decided that we don't actually need the ability to override the merge freeze start and stop for a particular Release. That came up while discussing the release cohort view, and I think we just neglected to come back to this story and remove that AC.

2021-09-15 17:11 UTC, Br4nd0R reviewed
This lgtm. @davisagli - I'll let you give the final rubber stamping.

2021-09-15 17:18 UTC, davisagli requested changes

2021-09-15 17:18 UTC, davisagli commented on metaci/release/models.py
> +        default="None",
When would we use status="None"? Should we remove that option and default to Planned?

2021-09-15 17:18 UTC, davisagli commented on metaci/release/models.py
> +        blank=False,
I think blank also needs to be set to True so that it's possible to edit the Release in the admin without setting a release cohort.

2021-09-15 18:01 UTC, davisagli approved these changes

2021-09-15 18:14 UTC, merged